[package]
name = "evtx-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
evtx = "0.7.2"
clap = {version = "3.2.11", features = ["derive"] }
csv = "1.1"

[build-dependencies]
static_vcruntime = "2.0"