# .github/workflows/build.yml
name: Build

on:
  push:
    tags:
      - *

jobs:
  build:
    name: release
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - run: cargo build --release